version: '3'
services:
  batnode1: 
    build: .
    container_name: batnode1
    ports:
      - "3001:3000"
    depends_on:
      - "mongodb" 
  batnode2: 
    container_name: batnode2
    build: .
    ports:
      - "3002:3000"
    depends_on:
      - "mongodb" 
  batnode3: 
    build: .
    container_name: batnode3
    ports:
      - "3003:3000"
    depends_on:
      - "mongodb" 
  nginx:
    image: "nginx"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./public/:/var/www/public/
    ports:
      - "80:80"
    depends_on:
      - "batnode1"
      - "batnode2"  
      - "batnode3" 
  mongodb:
    container_name: mongodb
    image: "mongo"
networks:
  network_hello_node:
    driver: bridge